### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by mzaini30** [turfaa/languagetool#2]
Input: `python langTool.py en_US cyanide-it.ts`

Output:

```
  File "langTool.py", line 86
SyntaxError: Non-ASCII character '\xe2' in file langTool.py on line 86, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

**Comment by turfaa** [comment]
@mzaini30 It is an encoding error. I've added different encoding support. Try to use `ISO-8859-1` encoding for your code. Checkout the updated readme for usage instruction.

Note : you have to use python3 to use this script

**Comment by mzaini30** [comment]
Okay, I will try again soon
