### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by arrizalamin** [turfaa/languagetool#3]
I notice your repository does not have a license. I suggest you use MIT, it's very permissive and let anyone to fork the project and redistribute with the same name. But if you want to go with WTFPL, I suggest you to look at [WTFNMFPL](https://tldrlegal.com/license/do-what-the-fuck-you-want-to-but-it's-not-my-fault-public-license-v1-(wtfnmfpl-1.0)) just in case you get sued if your project did something wrong. 😁

**Comment by turfaa** [comment]
@arrizalamin i used wtfpl because i just don't care about it :D

but, wtfnmfpl seems better. can you make  pull request about it for me? thanks
